# -*- coding: utf-8 -*-
"""ncvoters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-y97mU1UKYpGtQGYc8CLZ29Z7sZmP6d

# North Carolina Voter Registration Database

This notebook creates an SQLite database from publicly available voter registration data in North Carolina.  This information is maintained by the NC State Board of Elections and is updated every Saturday.

The file format is described at https://s3.amazonaws.com/dl.ncsbe.gov/data/layout_ncvoter.txt
"""

import pandas as pd

!head nc_voters.csv
!wc  nc_voters.csv

# Public S3 URL published by the NC State Board of Elections.
URL = "https://s3.amazonaws.com/dl.ncsbe.gov/data/ncvoter_Statewide.zip"

import os

# Output csv file that will contain our slimmed-down version of the database
OUTPUT_CSV = "nc_voters.csv"

# Delete the output CSV if it already exists
if os.path.exists(OUTPUT_CSV):
  os.remove(OUTPUT_CSV)
  print(f"Deleted existing file: {OUTPUT_CSV}")

"""We only want a subset of the columns.

Certain columns have additional whitespace that needs to be converted to just one space.
"""

import re

sanitized_columns = [
  'last_name',
  'first_name',
  'middle_name',
  'res_street_address',
  'res_city_desc'
]

def sanitize(text):
  if pd.isna(text): # Check for NaN or None
    return ''
  text = str(text) # Ensure it's a string
  text = re.sub(r'\s+', ' ', text)
  text = text.strip()
  return text

"""Create the map of county numbers to county names."""

from numpy._core.defchararray import count
import urllib.request
import re

LAYOUT_URL = "https://s3.amazonaws.com/dl.ncsbe.gov/data/layout_ncvoter.txt"
txt = urllib.request.urlopen(LAYOUT_URL).read()
lines = [line.decode('utf-8') for line in txt.splitlines()]
county_map = {}

keep = False

for line in lines:
    if line.startswith("ALAMANCE"):
        keep = True
    if keep:
        name, number = line.split()
        number = int(number)
        number = f"{number:02d}"
        county_map[number] = name
    if line.startswith("YANCEY") and keep:
        break

print(f"Found {len(county_map)} counties")

print(county_map)

"""Read and process the zip file in chunks of 100,000 records (so as not to exhaust memory).  There are about 90-95 chunks in the file."""

chunks = pd.read_csv(URL,
                     compression='zip',
                     sep='\t',
                     encoding='latin1',
                     chunksize=100000,
                     low_memory=False)

total_rows = 0
for i, chunk in enumerate(chunks):
  print(f"Processing chunk {i+1}")

  # Only active voters
  chunk = chunk[chunk['status_cd'] == 'A'].copy()

  # Clean unnecessary whitespace
  for col in sanitized_columns:
    if col in chunk.columns:
      chunk[col] = chunk[col].apply(sanitize)
  total_rows += len(chunk)

  # Add county names
  # Convert county_id to string to ensure keys match county_map's string keys
  chunk['county_id'] = chunk['county_id'].astype(str)
  # Use .map() to add county names, handling missing keys by assigning NaN
  chunk['county'] = chunk['county_id'].map(county_map)

  # Rename columns
  chunk = chunk.rename(
      columns = {
          "res_street_address": "address",
          "res_city_desc": "city",
          "state_cd": "state",
          "zip_code": "zip",
          "full_phone_number": "phone",
          "race_code": "race",
          "party_cd": "party",
          "gender_code": "gender",
          "birth_year": "birth_year",
          "age_at_year_end": "age",
      }
  )
  # Extract a subset
  chunk = chunk[['last_name', 'first_name', 'middle_name', 'address', 'city',
                 'county', 'state', 'zip', 'phone', 'race', 'party', 'gender',
                 'birth_year', 'age', 'birth_state']]

  # We only want headers on the first chunk (i == 0)
  chunk.to_csv(OUTPUT_CSV, mode='a', header=(i == 0), index=False)

print(f"Done. {total_rows} rows imported into {OUTPUT_CSV}.")

!head nc_voters.csv

# Mount Google Drive
#from google.colab import drive
#drive.mount('/content/drive')

import shutil
import os


# Define the destination folder in Google Drive
gdrive_destination_folder = '/content/drive/MyDrive/Colab Notebooks/data'

# Ensure the destination folder exists in Google Drive
os.makedirs(gdrive_destination_folder, exist_ok=True)

# Copy the output CSV to Google Drive
shutil.copy(OUTPUT_CSV, gdrive_destination_folder)
print(f"Copied {OUTPUT_CSV} to {gdrive_destination_folder}/")

