PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE reasons(
  reason_cd TEXT,
  voter_status_reason_desc TEXT
);
INSERT INTO reasons VALUES('A1','UNVERIFIED');
INSERT INTO reasons VALUES('A2','CONFIRMATION PENDING');
INSERT INTO reasons VALUES('AA','ARMED FORCES');
INSERT INTO reasons VALUES('AL','LEGACY DATA');
INSERT INTO reasons VALUES('AN','UNVERIFIED NEW');
INSERT INTO reasons VALUES('AP','VERIFICATION PENDING');
INSERT INTO reasons VALUES('AV','VERIFIED');
INSERT INTO reasons VALUES('DI','UNAVAILABLE ESSENTIAL INFORMATION');
INSERT INTO reasons VALUES('DN','CONFIRMATION NOT RETURNED');
INSERT INTO reasons VALUES('DU','VERIFICATION RETURNED UNDELIVERABLE');
INSERT INTO reasons VALUES('IA','ADMINISTRATIVE');
INSERT INTO reasons VALUES('IL','LEGACY - CONVERSION');
INSERT INTO reasons VALUES('IN','CONFIRMATION NOT RETURNED');
INSERT INTO reasons VALUES('IU','CONFIRMATION RETURNED UNDELIVERABLE');
INSERT INTO reasons VALUES('R2','DUPLICATE');
INSERT INTO reasons VALUES('RA','ADMINISTRATIVE');
INSERT INTO reasons VALUES('RC','REMOVED DUE TO SUSTAINED CHALLENGE');
INSERT INTO reasons VALUES('RD','DECEASED');
INSERT INTO reasons VALUES('RF','FELONY CONVICTION');
INSERT INTO reasons VALUES('RH','MOVED WITHIN STATE');
INSERT INTO reasons VALUES('RL','MOVED FROM COUNTY');
INSERT INTO reasons VALUES('RM','REMOVED AFTER 2 FED GENERAL ELECTIONS IN INACTIVE STATUS');
INSERT INTO reasons VALUES('RP','REMOVED UNDER OLD PURGE LAW');
INSERT INTO reasons VALUES('RQ','REQUEST FROM VOTER');
INSERT INTO reasons VALUES('RR','FELONY SENTENCE COMPLETED');
INSERT INTO reasons VALUES('RS','MOVED FROM STATE');
INSERT INTO reasons VALUES('RT','TEMPORARY REGISTRANT');
INSERT INTO reasons VALUES('SM','MILITARY');
INSERT INTO reasons VALUES('SO','OVERSEAS CITIZEN');
COMMIT;
